"""admin roles, login events, and their retention window

Revision ID: 111eef9cd430
Revises: f079ee7422e3
Create Date: 2026-09-02 15:13:43.112333

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '111eef9cd430'
down_revision: str | None = 'f079ee7422e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('site_settings', sa.Column('login_event_retention_days', sa.Integer(), server_default='365', nullable=False))
    op.add_column('users', sa.Column('admin_role', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###

    # Data backfill: every existing admin becomes a "full" admin -- the tier that matches
    # everything is_admin has always meant up to this point. New nullable admin_role also reads
    # as "full" in code wherever it's checked (see User.admin_role's docstring), so this backfill
    # is belt-and-suspenders, not load-bearing -- but keeping the column populated for existing
    # rows is still the honest state to leave the data in.
    op.execute("UPDATE users SET admin_role = 'full' WHERE is_admin = true")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_role')
    op.drop_column('site_settings', 'login_event_retention_days')
    op.drop_table('login_events')
    # ### end Alembic commands ###
