"""add_nda_acceptance

Revision ID: 2c9e63f37bd8
Revises: 70a1fa23ae13
Create Date: 2026-08-19 09:55:01.788689

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2c9e63f37bd8'
down_revision: str | None = '70a1fa23ae13'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('nda_required', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('nda_accepted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nda_accepted_at')
    op.drop_column('site_settings', 'nda_required')
    # ### end Alembic commands ###
