"""add_vocal_goals_and_coach_exercise_extensions

Revision ID: 3a9025c9c0b4
Revises: 738a7b99c591
Create Date: 2026-08-13 17:34:35.081633

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3a9025c9c0b4'
down_revision: str | None = '738a7b99c591'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocal_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_low_note', sa.String(length=10), nullable=True),
    sa.Column('target_avg_note', sa.String(length=10), nullable=True),
    sa.Column('target_high_note', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('coach_assignments', sa.Column('exercise_tone_targets', sa.JSON(), nullable=True))
    op.add_column('exercises', sa.Column('created_by_coach_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'exercises', 'coach_profiles', ['created_by_coach_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'created_by_coach_id')
    op.drop_column('coach_assignments', 'exercise_tone_targets')
    op.drop_table('vocal_goals')
    # ### end Alembic commands ###
