"""add unique constraint on baselines user_id metric_name

Revision ID: 4911280098d3
Revises: 72859132d602
Create Date: 2026-08-10 19:46:01.131592

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4911280098d3'
down_revision: str | None = '72859132d602'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_baseline_user_metric', 'baselines', ['user_id', 'metric_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_baseline_user_metric', 'baselines', type_='unique')
    # ### end Alembic commands ###
