"""drop unused song analyzer tables

Revision ID: 65b7e96919a2
Revises: 66eddf508177
Create Date: 2026-08-11 20:04:10.052492

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '65b7e96919a2'
down_revision: str | None = '66eddf508177'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reordered from autogenerate: song_analyses (the FK-dependent child table) must drop
    # before songs, or Postgres refuses with DependentObjectsStillExist.
    op.drop_table('song_analyses')
    op.drop_table('songs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_analyses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('song_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('detected_key', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('vocal_range_low', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('vocal_range_high', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('highest_passage_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lowest_passage_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('phrase_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('breath_locations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('song_analyses_song_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('song_analyses_pkey')),
    sa.UniqueConstraint('song_id', name=op.f('song_analyses_song_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('songs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('artist', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('original_key', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('songs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('songs_pkey'))
    )
    # ### end Alembic commands ###
