"""add longest voiced run seconds to acoustic measurements

Revision ID: 66eddf508177
Revises: cdea6917203b
Create Date: 2026-08-11 19:36:36.456981

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '66eddf508177'
down_revision: str | None = 'cdea6917203b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acoustic_measurements', sa.Column('longest_voiced_run_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acoustic_measurements', 'longest_voiced_run_seconds')
    # ### end Alembic commands ###
