"""add_site_settings

Revision ID: 70a1fa23ae13
Revises: 328ea2ba34e8
Create Date: 2026-08-15 11:40:03.853044

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '70a1fa23ae13'
down_revision: str | None = '328ea2ba34e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signups_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("INSERT INTO site_settings (id, signups_enabled) VALUES (1, true)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
