"""add pitch_stability_semitones to acoustic_measurements

Revision ID: 72859132d602
Revises: c5b63b733546
Create Date: 2026-08-10 16:46:01.443198

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '72859132d602'
down_revision: str | None = 'c5b63b733546'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acoustic_measurements', sa.Column('pitch_stability_semitones', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acoustic_measurements', 'pitch_stability_semitones')
    # ### end Alembic commands ###
