"""add_coach_pilot_tables

Revision ID: 738a7b99c591
Revises: 65b7e96919a2
Create Date: 2026-08-12 16:02:04.869181

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '738a7b99c591'
down_revision: str | None = '65b7e96919a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('studio_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('coach_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('singer_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['singer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coach_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('singer_user_id', sa.UUID(), nullable=False),
    sa.Column('invite_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invite_id'], ['coach_invites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['singer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'singer_user_id', name='uq_coach_access_pair')
    )
    op.create_index('uq_one_active_coach_per_singer', 'coach_access', ['singer_user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('coach_access_category_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coach_access_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_access_id'], ['coach_access.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_access_id', 'category', name='uq_grant_access_category')
    )
    op.create_table('coach_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('singer_user_id', sa.UUID(), nullable=False),
    sa.Column('coach_access_id', sa.UUID(), nullable=False),
    sa.Column('exercise_ids', sa.JSON(), nullable=False),
    sa.Column('note_to_singer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_access_id'], ['coach_access.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['singer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coach_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('singer_user_id', sa.UUID(), nullable=False),
    sa.Column('coach_access_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('flagged_terms', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_access_id'], ['coach_access.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['singer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('consent_records', sa.Column('category', sa.String(length=50), nullable=True))
    op.create_foreign_key(
        'fk_consent_records_clinician_id_coach_profiles',
        'consent_records', 'coach_profiles', ['clinician_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_consent_records_clinician_id_coach_profiles', 'consent_records', type_='foreignkey'
    )
    op.drop_column('consent_records', 'category')
    op.drop_table('coach_notes')
    op.drop_table('coach_assignments')
    op.drop_table('coach_access_category_grants')
    op.drop_index('uq_one_active_coach_per_singer', table_name='coach_access', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('coach_access')
    op.drop_table('coach_invites')
    op.drop_table('coach_profiles')
    # ### end Alembic commands ###
