"""add_tone_game_tables

Revision ID: b549a62d3e6b
Revises: 059761a907fa
Create Date: 2026-08-25 19:24:35.893286

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b549a62d3e6b'
down_revision: str | None = '059761a907fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tone_game_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tone_game_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_note', sa.String(length=10), nullable=False),
    sa.Column('target_hz', sa.Float(), nullable=False),
    sa.Column('detected_hz', sa.Float(), nullable=True),
    sa.Column('semitones_off', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('hold_fraction', sa.Float(), nullable=False),
    sa.Column('reaction_ms', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tone_game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tone_game_attempts')
    op.drop_table('tone_game_sessions')
    # ### end Alembic commands ###
