"""add_user_username

Revision ID: bc47c08750c5
Revises: cd22c0f537c3
Create Date: 2026-09-01 20:14:11.873200

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bc47c08750c5'
down_revision: str | None = 'cd22c0f537c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
