"""add voice_use to user_profiles

Revision ID: c5b63b733546
Revises: ac27ac0749e9
Create Date: 2026-08-08 20:00:37.964507

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c5b63b733546'
down_revision: str | None = 'ac27ac0749e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('voice_use', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'voice_use')
    # ### end Alembic commands ###
