"""add_coach_access_reassessment_date

Revision ID: cd22c0f537c3
Revises: b549a62d3e6b
Create Date: 2026-09-01 19:53:33.818973

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cd22c0f537c3'
down_revision: str | None = 'b549a62d3e6b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_access', sa.Column('next_reassessment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach_access', 'next_reassessment_date')
    # ### end Alembic commands ###
