"""recording audio purge fields and site settings retention windows

Revision ID: f079ee7422e3
Revises: 19e3c8602b1a
Create Date: 2026-09-02 14:46:34.929281

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f079ee7422e3'
down_revision: str | None = '19e3c8602b1a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('audio_purged_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('recordings', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.add_column('site_settings', sa.Column('recording_retention_days', sa.Integer(), server_default='90', nullable=False))
    op.add_column('site_settings', sa.Column('checkin_notes_retention_days', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'checkin_notes_retention_days')
    op.drop_column('site_settings', 'recording_retention_days')
    op.alter_column('recordings', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('recordings', 'audio_purged_at')
    # ### end Alembic commands ###
